// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBFJsq6rB2Ivm2bhN3JrFVgdoX5rGNIY',
    appId: '1:472889108034:web:0eb3929a9aef85f6c56fdb',
    messagingSenderId: '472889108034',
    projectId: 'taskflow-app-8b1f6',
    authDomain: 'taskflow-app-8b1f6.firebaseapp.com',
    storageBucket: 'taskflow-app-8b1f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LkeavppOsLr_kYUtylkCtzakHiS0kck',
    appId: '1:472889108034:android:c36df6205f0c40e7c56fdb',
    messagingSenderId: '472889108034',
    projectId: 'taskflow-app-8b1f6',
    storageBucket: 'taskflow-app-8b1f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1uLR_HjNbGHm7KgGmD1yrf1kWzot2HE',
    appId: '1:472889108034:ios:7065b269b161b5f1c56fdb',
    messagingSenderId: '472889108034',
    projectId: 'taskflow-app-8b1f6',
    storageBucket: 'taskflow-app-8b1f6.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1uLR_HjNbGHm7KgGmD1yrf1kWzot2HE',
    appId: '1:472889108034:ios:7065b269b161b5f1c56fdb',
    messagingSenderId: '472889108034',
    projectId: 'taskflow-app-8b1f6',
    storageBucket: 'taskflow-app-8b1f6.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDBFJsq6rB2Ivm2bhN3JrFVgdoX5rGNIY',
    appId: '1:472889108034:web:e372eca742cd20b3c56fdb',
    messagingSenderId: '472889108034',
    projectId: 'taskflow-app-8b1f6',
    authDomain: 'taskflow-app-8b1f6.firebaseapp.com',
    storageBucket: 'taskflow-app-8b1f6.firebasestorage.app',
  );
}
